#!/usr/bin/env python3
"""
generate_index.py — turn data/whitepapers.json into a browsable Markdown index
(data/INDEX.md) plus a stats snippet (data/STATS.md) the README can embed.
"""
from __future__ import annotations
import collections
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"


def md_escape(s: str) -> str:
    return s.replace("|", "\\|").replace("\n", " ").strip()


def social_cell(socials: dict) -> str:
    if not socials:
        return ""
    parts = []
    for plat, handles in socials.items():
        parts.append(f"{plat}:{handles[0]}")
    return md_escape(", ".join(parts[:4]))


def wallet_cell(wallets: dict) -> str:
    addrs = []
    for v in wallets.values():
        addrs.extend(v)
    if not addrs:
        return ""
    a = addrs[0]
    short = a if len(a) <= 14 else f"{a[:6]}…{a[-4:]}"
    extra = f" (+{len(addrs)-1})" if len(addrs) > 1 else ""
    return f"`{short}`{extra}"


def main() -> None:
    recs = json.loads((DATA / "whitepapers.json").read_text(encoding="utf-8"))
    recs.sort(key=lambda r: r["name"].lower())

    # ---- INDEX.md ----
    lines = [
        "# 📇 Whitepaper Index",
        "",
        f"All **{len(recs)}** whitepapers with auto-extracted metadata. "
        "Generated by [`tools/generate_index.py`](../tools/generate_index.py) — do not edit by hand.",
        "",
        "Columns: **Year** = most-cited year in the doc · **Team** = role-confirmed "
        "names · **Socials** = first handle per platform · **Wallet** = first address "
        "found (⚠️ may be an example/donation address, verify before trusting).",
        "",
    ]

    # A–Z jump navigation
    def bucket(name: str) -> str:
        c = name[:1].upper()
        return c if c.isalpha() else "#"
    present = sorted({bucket(r["name"]) for r in recs})
    nav = " · ".join(f"[{c}](#{c.lower() if c != '#' else 'sym'})" for c in present)
    lines += [f"**Jump to:** {nav}", "", "[↑ Back to README](../README.md)", ""]

    cur = None
    for i, r in enumerate(recs, 1):
        b = bucket(r["name"])
        if b != cur:
            cur = b
            anchor = b.lower() if b != "#" else "sym"
            lines += ["", f'<a id="{anchor}"></a>', f"### {b}", "",
                      "| # | Whitepaper | Year | Team | Socials | Wallet |",
                      "|---|------------|------|------|---------|--------|"]
        name = md_escape(r["name"])
        # INDEX.md lives in data/, PDFs live in pdfs/ → hop up then into pdfs/
        link = "../pdfs/" + r["file"].replace(" ", "%20")
        year = (r.get("dates") or {}).get("likely_year") or ""
        team = md_escape(", ".join(r["people"]["team"][:3]))
        socials = social_cell(r["socials"])
        wallet = wallet_cell(r["wallets"])
        lines.append(
            f"| {i} | [{name}]({link}) | {year} | {team} | {socials} | {wallet} |")
    (DATA / "INDEX.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    # ---- STATS.md (README embed) ----
    has_text = [r for r in recs if r["has_text"]]
    years = collections.Counter(
        r["dates"]["likely_year"] for r in has_text if r["dates"].get("likely_year"))
    socials = collections.Counter()
    for r in recs:
        for k in r["socials"]:
            socials[k] += 1
    eth = sum(len(r["wallets"].get("eth_evm", [])) for r in recs)
    btc = sum(len(r["wallets"].get("btc_legacy", [])) +
              len(r["wallets"].get("btc_bech32", [])) for r in recs)

    year_bar = []
    for y in range(2013, 2023):
        n = years.get(y, 0)
        bar = "█" * round(n / 8)
        year_bar.append(f"  {y}  {bar} {n}")

    s = [
        "<!-- generated by tools/generate_index.py -->",
        "```",
        "Whitepapers ............ {:>5}".format(len(recs)),
        "With extractable text .. {:>5}".format(len(has_text)),
        "Scanned (image-only) ... {:>5}".format(len(recs) - len(has_text)),
        "Dated ................. {:>5}".format(sum(1 for r in has_text if r['dates'].get('likely_year'))),
        "With team names ........ {:>5}".format(sum(1 for r in recs if r['people']['team'])),
        "With social links ...... {:>5}".format(sum(1 for r in recs if r['socials'])),
        "With wallet addresses .. {:>5}  ({} ETH/EVM, {} BTC)".format(
            sum(1 for r in recs if r['wallets']), eth, btc),
        "```",
        "",
        "**Publication years (the ICO boom in one chart):**",
        "```",
        *year_bar,
        "```",
        "",
        "**Social platforms linked across the archive:**",
        "",
        "| Platform | Papers |",
        "|----------|-------:|",
        *[f"| {k.title()} | {v} |" for k, v in socials.most_common()],
    ]
    (DATA / "STATS.md").write_text("\n".join(s) + "\n", encoding="utf-8")
    print(f"Wrote data/INDEX.md ({len(recs)} rows) and data/STATS.md")


if __name__ == "__main__":
    main()
